@startuml

title __RISK's Class Diagram__\n

  namespace Runner {
    class Runner.Runner {
    }
  }
  

  namespace Runner {
    class Runner.ExtractedTasks {
    }
  }
  

  namespace Runner {
    enum tasksEnum {
    }
  }
  

  namespace GameLogic {
    class GameLogic.Card {
    }
  }
  

  namespace GameLogic {
    class GameLogic.CardPlay {
    }
  }
  

  namespace GameLogic {
    class GameLogic.Continent {
    }
  }
  

  namespace GameLogic {
    class GameLogic.Country {
    }
  }
  

  namespace GameLogic {
    class GameLogic.CurrentPlayer {
    }
  }
  

  namespace GameLogic {
    class GameLogic.Database {
    }
  }
  

  namespace GameLogic {
    class GameLogic.GamePlay {
    }
  }
  

  namespace GameLogic {
    class GameLogic.GameSubject {
    }
  }
  

  namespace GameLogic {
    class GameLogic.Graph {
    }
  }
  

  namespace GameLogic {
    interface GameLogic.ISubject {
    }
  }
  

  namespace GameLogic {
    class GameLogic.Mapx {
    }
  }
  

  namespace GameLogic {
    class GameLogic.Player {
    }
  }
  

  namespace GameLogic {
    enum State {
    }
  }
  

  namespace GameLogic {
    enum cardType {
    }
  }
  

  namespace View {
    class View.CardExchange {
    }
  }
  

  namespace View {
    interface View.IObserver {
    }
  }
  

  namespace View {
    class View.PhaseView {
    }
  }
  

  namespace View {
    class View.Runner {
    }
  }
  

  Runner.Runner o-- Runner.tasksEnum : currentTask
  Runner.Runner o-- GameLogic.GamePlay : gamePlayObj
  Runner.ExtractedTasks o-- Runner.tasksEnum : name
  GameLogic.Card o-- GameLogic.cardType : cType
  GameLogic.CurrentPlayer o-- GameLogic.CardPlay : cardPlayObj
  GameLogic.CurrentPlayer o-- GameLogic.Player : currentPlayer
  GameLogic.GamePlay o-- View.CardExchange : cardExchangeView
  GameLogic.GamePlay o-- GameLogic.GameSubject : gameSubjectObj
  GameLogic.GamePlay o-- GameLogic.CardPlay : cardPlayObj
  GameLogic.GamePlay o-- GameLogic.CurrentPlayer : currentPlayerObj
  GameLogic.GamePlay o-- GameLogic.State : currentState
  GameLogic.GamePlay o-- GameLogic.Database : databaseObj
  GameLogic.GamePlay o-- GameLogic.Graph : graphObj
  GameLogic.GamePlay o-- GameLogic.Mapx : mapxObj
  GameLogic.GameSubject .up.|> GameLogic.ISubject
  GameLogic.GameSubject o-- GameLogic.State : currentState
  GameLogic.Mapx o-- GameLogic.Database : database
  View.CardExchange .up.|> View.IObserver
  View.PhaseView .up.|> View.IObserver


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
